### ISSUE TITLE
Создать юниттесты

### ISSUE THREAD

**Issue by MrPaschenko** [MrPaschenko/op-course-work#15]
Тестирование: [юниттесты с примерами](https://youtu.be/CszugIag2TA)
Тестирование: https://github.com/HowProgrammingWorks/Testing
Юниттесты: https://github.com/HowProgrammingWorks/Unittesting

**Comment by akaeyuhi** [comment]
Уже есть аналогичное предложение
https://github.com/MrPaschenko/op-coursework/issues/2
